[log]
level = "info"

[log.file.basic]
level = "info"
filename = "./prod.log"

[httpserver]
addr = "0.0.0.0:10001"
enable_debug = true

[grpcserver]
addr = "0.0.0.0:10002"

[etcd]
addr = "0.0.0.0:2379"

[handler]
need_grpc=true
name="base"

[grpc.base]

[worker.hello_world]
